export const myProjects = [
  {
    id: 200,
    category: ["react", "js", "node"],
    title: "X Twitter App",
    title2: "A Twitter UI clone allowing users to post tweets and interact with posts, built using React and Node.",
    para1: "#html",
    para2: "#css",
    para3: "#js",
    para4: "#bootstrap",
    img: "/img/img-pro/Screenshot 2024-08-03 174738.png",
    link: "https://twitter-ui-lemon.vercel.app",
  },
  {
    id: 200,
    category: ["react", "js", "node"],
    title: "Movies App Clone",
    title2: "A movie browsing app displaying trending movies with details and ratings, built with React and API integration.",
    para1: "#html",
    para2: "#css",
    para3: "#js",
    para4: "#bootstrap",
    img: "/img/img-pro/Screenshot 2025-06-26 181740.png",
    link: "https://movies-clon.vercel.app",
  },
  {
    id: 200,
    category: ["react", "js", "node"],
    title: "Notes App ",
    title2: "A simple Notes App to create, edit, and organize your notes with tags and search.",
    para1: "#html",
    para2: "#css",
    para3: "#js",
    para4: "#bootstrap",
    img: "/img/img-pro/Screenshot 2025-10-26 014546.png",
    link: "https://movies-clon.vercel.app",
  },
  {
    id: 0,
    category: ["css"],
    title: "E-commerce Shop",
    title2: "A responsive e-commerce frontend to display products with a clean and simple design using HTML, CSS, and JS.",
    para1: "#html",
    para2: "#css",
    para3: "#js",
    para4: "#bootstrap",
    img: "/img/img-pro/Screenshot 2023-05-07 105731.png",
    link: "https://notes-app-mocha-eight.vercel.app/",
  },
  {
    id: 1,
    category: ["react", "js"],
    title: "Amazon Clone",
    title2: "An Amazon-like e-commerce frontend with product listings and a cart system, built using React and Firebase.",
    para1: "#REACT",
    para2: "#css",
    para3: "#js",
    para4: "#bootstrap",
    img: "img/img-pro/Screenshot 2023-03-27 155815.png",
    link: "https://clone-dffaf.web.app/",
  },
  {
    id: 2,
    category: ["js"],
    title: "CRUD Operations System",
    title2: "A CRUD system allowing users to add, edit, and delete data using JavaScript with LocalStorage for data persistence.",
    para1: "#REACT",
    para2: "#css",
    para3: "#js",
    para4: "#bootstrap",
    img: "img/img-pro/Screenshot 2023-08-05 012749.png",
    link: "https://crud-opration-sys.vercel.app/",
  },
  {
    id: 3,
    category: ["js"],
    title: "Movies Black",
    title2: "A movie app with a clean dark theme that displays trending movies and their details using JS and API.",
    para1: "#html",
    para2: "#css",
    para3: "#js",
    para4: "#bootstrap",
    img: "img/img-pro/Screenshot 2023-05-25 222930.png",
    link: "https://movis-api-two.vercel.app/",
  },
  {
    id: 5,
    category: ["react", "js"],
    title: "Full Movies",
    title2: "A movie browsing app with detailed pages for each movie, ratings, and API data integration, built with React.",
    para1: "#html",
    para2: "#css",
    para3: "#js",
    para4: "#bootstrap",
    img: "img/img-pro/moveis.png",
    link: "https://full-movies-blue.vercel.app/",
  },
  {
    id: 6,
    category: ["react", "js"],
    title: "Movies Watched",
    title2: "An app for tracking and listing the movies you've watched, with notes and status management using React.",
    para1: "#React.js",
    img: "img/img-pro/Screenshot 2023-11-14 205338.png",
    link: "https://movies-list-beige.vercel.app/",
  },
  {
    id: 6,
    category: ["js"],
    title: "Todo List",
    title2: "A simple to-do list app allowing users to add and remove daily tasks, built with JavaScript for practice.",
    para1: "#React.js",
    img: "img/img-pro/todolist.png",
    link: "https://todo-list-js-murex.vercel.app/",
  },
  {
    id: 7,
    category: ["react", "js"],
    title: "Amazon Full E-commerce",
    title2: "A complete Amazon e-commerce clone with advanced cart functionalities and user-friendly design, built using React.",
    para1: "#React.js",
    img: "img/img-pro/Screenshot 2023-11-15 163404.png",
    link: "https://clone-dffaf.web.app/",
  },
  {
    id: 1,
    category: ["css"],
    title: "Topico Shop",
    title2: "A responsive mobile store frontend showcasing smartphone products using clean UI built with HTML, CSS, and JS.",
    para1: "#html",
    para2: "#css",
    para3: "#js",
    para4: "#bootstrap",
    img: "/img/img-pro/afa23bac-766f-48e6-a676-7688daeabc2f.png",
    link: "https://phone-shop-com.vercel.app/",
  },
  {
    id: 2,
    category: ["css"],
    title: "Food Website",
    title2: "A clean restaurant website displaying food menus with a visually appealing layout using HTML, CSS, and JS.",
    para1: "#html",
    para2: "#css",
    para3: "#js",
    para4: "#bootstrap",
    img: "img/img-pro/Screenshot 2023-03-12 231008.png",
    link: "https://food-website-livid.vercel.app/",
  },
  {
    id: 3,
    category: ["js", "css"],
    title: "Beats Website",
    title2: "A product showcase site for Beats headphones with a sleek and modern design using HTML, CSS, and JavaScript.",
    para1: "#html",
    para2: "#css",
    para3: "#js",
    para4: "#bootstrap",
    img: "img/img-pro/Screenshot 2023-03-31 170144.png",
    link: "https://beats-website-orcin.vercel.app/",
  },
  {
    id: 3,
    category: ["css"],
    title: "Woodex Shop",
    title2: "An online furniture shop frontend with a clean, modern design, showcasing products using HTML, CSS, and JS.",
    para1: "#html",
    para2: "#css",
    para3: "#js",
    para4: "#bootstrap",
    img: "img/img-pro/Screenshot 2023-08-04 213932.png",
    link: "https://woodex-master-shop.vercel.app/",
  },
  {
    id: 4,
    category: ["css"],
    title: "Kitter Shop",
    title2: "A responsive pet shop website showcasing pet products and accessories using HTML, CSS, and JavaScript.",
    para1: "#html",
    para2: "#css",
    para3: "#js",
    para4: "#bootstrap",
    img: "img/img-pro/Screenshot 2023-08-04 213852.png",
    link: "https://kitter-master-shop.vercel.app/",
  },
  {
    id: 5,
    category: ["css"],
    title: "Halloween Website",
    title2: "A festive Halloween-themed website with animations and themed colors using HTML, CSS, and JavaScript.",
    para1: "#html",
    para2: "#css",
    para3: "#js",
    para4: "#bootstrap",
    img: "img/img-pro/Screenshot 2023-08-04 213714.png",
    link: "https://halloween-zeta-mocha.vercel.app/",
  },
  {
    id: 6,
    category: ["css"],
    title: "Filmlane Best Movies",
    title2: "A movie collection website showcasing trending movies with categories, built with HTML, CSS, and JavaScript.",
    para1: "#html",
    para2: "#css",
    para3: "#js",
    para4: "#bootstrap",
    img: "img/img-pro/Screenshot 2023-03-12 230823.png",
    link: "https://filmlane-best-movie-collections-main.vercel.app/",
  },
  {
    id: 7,
    category: ["css"],
    title: "Book Doctors Website",
    title2: "A medical appointment booking website with a clean, professional layout using HTML, CSS, and JavaScript.",
    para1: "#html",
    para2: "#css",
    para3: "#js",
    para4: "#bootstrap",
    img: "img/img-pro/Screenshot 2023-03-31 170157.png",
    link: "https://book-doctors-website-delta.vercel.app/",
  },
  {
    id: 8,
    category: ["css"],
    title: "Cars Website",
    title2: "A car dealership frontend displaying car models with a modern layout using HTML, CSS, and JavaScript.",
    para1: "#html",
    para2: "#css",
    para3: "#js",
    para4: "#bootstrap",
    img: "img/img-pro/Screenshot 2023-03-31 170212.png",
    link: "https://cars-website-two.vercel.app/",
  },
  {
    id: 9,
    category: ["css"],
    title: "Mc-Foodi Website",
    title2: "A fast-food restaurant landing page displaying menu items with a clean, colorful UI using HTML, CSS, and JS.",
    para1: "#html",
    para2: "#css",
    para3: "#js",
    para4: "#bootstrap",
    img: "img/img-pro/Screenshot 2023-03-31 174344.png",
    link: "https://mc-foodi-website.vercel.app/",
  },
  {
    id: 10,
    category: ["css"],
    title: "Plants Website",
    title2: "A nature-themed plants e-commerce frontend showcasing plants for sale using HTML, CSS, and JavaScript.",
    para1: "#html",
    para2: "#css",
    para3: "#js",
    para4: "#bootstrap",
    img: "img/img-pro/Screenshot 2023-03-31 170013.png",
    link: "https://plants-website-khaki.vercel.app/",
  },
  {
    id: 11,
    category: ["css"],
    title: "Netflix Clone",
    title2: "A Netflix landing page clone showcasing movie posters and categories using HTML, CSS, and JavaScript.",
    para1: "#html",
    para2: "#css",
    para3: "#js",
    para4: "#bootstrap",
    img: "img/img-pro/Screenshot 2023-03-31 170052.png",
    link: "https://netflixx-six.vercel.app/",
  },
  {
    id: 12,
    category: ["css"],
    title: "Appie Clone",
    title2: "A landing page clone of Appie showcasing product features with a clean design using HTML, CSS, and JS.",
    para1: "#html",
    para2: "#css",
    para3: "#js",
    para4: "#bootstrap",
    img: "img/img-pro/Screenshot 2023-03-31 170131.png",
    link: "https://appie-clone.vercel.app/",
  },
  {
    id: 13,
    category: ["css"],
    title: "Facebook Clone",
    title2: "A Facebook login and feed interface clone with a clean, responsive design using HTML, CSS, and JavaScript.",
    para1: "#html",
    para2: "#css",
    para3: "#js",
    para4: "#bootstrap",
    img: "img/img-pro/Screenshot 2023-03-20 000335.png",
    link: "https://facebook-colon-one.vercel.app/",
  },
  {
    id: 14,
    category: ["react"],
    title: "Otere Portfolio React",
    title2: "A personal portfolio website showcasing projects and skills, built using React for dynamic rendering.",
    para1: "#REACT",
    para2: "#css",
    para3: "#js",
    para4: "#bootstrap",
    img: "img/img-pro/Screenshot 2023-03-31 173738.png",
    link: "https://otere-portfolio-react.vercel.app/",
  },
  {
    id: 16,
    category: ["css"],
    title: "Alfy Website",
    title2: "A small business landing page showcasing services and contact details using HTML, CSS, and JavaScript.",
    para1: "#html",
    para2: "#css",
    para3: "#js",
    para4: "#bootstrap",
    img: "img/img-pro/Screenshot 2023-03-31 174218.png",
    link: "https://alfy-website.vercel.app/",
  },
  {
    id: 18,
    category: ["css"],
    title: "Crafti Shop",
    title2: "A crafts and handmade products online shop with a clean, attractive layout using HTML, CSS, and JavaScript.",
    para1: "#html",
    para2: "#css",
    para3: "#js",
    para4: "#bootstrap",
    img: "img/img-pro/Screenshot 2023-08-04 213045.png",
    link: "https://crafti-shop.vercel.app/",
  },
  {
    id: 19,
    category: ["css"],
    title: "5amsat Clone",
    title2: "A simple freelance micro-services marketplace landing page clone using HTML, CSS, and JavaScript.",
    para1: "#html",
    para2: "#css",
    para3: "#js",
    para4: "#bootstrap",
    img: "img/img-pro/Screenshot 2023-03-31 170108.png",
    link: "https://5amsat-clone.vercel.app/",
  },
  {
    id: 20,
    category: ["css"],
    title: "Glowing Shop",
    title2: "A beauty and glowing products online shop frontend using HTML, CSS, and JavaScript with a clean design.",
    para1: "#REACT",
    para2: "#css",
    para3: "#js",
    para4: "#bootstrap",
    img: "img/img-pro/Screenshot 2023-08-04 213657.png",
    link: "https://glowing-shop.vercel.app/",
  },
  {
    id: 20,
    category: ["react", "js"],
    title: "LinkedIn Clone",
    title2: "A LinkedIn UI clone showcasing posts and profile sections, built using React for practice and learning.",
    para1: "#REACT",
    para2: "#css",
    para3: "#js",
    para4: "#bootstrap",
    img: "img/img-pro/Screenshot 2023-11-28 212732.png",
    link: "https://linked-in-uj5p.vercel.app/",
  },
  {
    id: 21,
    category: ["react", "js"],
    title: "Tic Tac Toe Game",
    title2: "A classic Tic Tac Toe game with a clean UI and interactive gameplay, built using React for learning purposes.",
    para1: "#REACT",
    para2: "#css",
    para3: "#js",
    para4: "#bootstrap",
    img: "img/img-pro/XOGAME.png",
    link: "https://tic-tac-toe-game-git-main-mohammed2207.vercel.app/",
  },
  {
    id: 22,
    category: ["react", "js"],
    title: "Calculator App iOS",
    title2: "An iOS-style calculator app with interactive buttons and smooth calculations, built using React.",
    para1: "#REACT",
    para2: "#css",
    para3: "#js",
    para4: "#bootstrap",
    img: "img/img-pro/blackboard-inscribed-with-scientific-formulas-calculations22.jpg",
    link: "https://calculator-ios-app-git-main-mohammed2207.vercel.app/",
  },
  {
    id: 23,
    category: ["react", "js", "node"],
    title: "Airbnb Clone",
    title2: "An Airbnb UI clone displaying property listings with filtering and details, built using Next.js and Tailwind.",
    para1: "#Next",
    para2: "#Tailwind",
    para3: "#ts",
    para4: "#jsx",
    img: "img/img-pro/Airbnbclone.png",
    link: "https://airbnb-clone-cmng8hpf2-mohammed2207.vercel.app/",
  },
];
